title: COMPLEXCITY 
description: #> # this means to ignore newlines until "baseurl:"
  Author -- Vaishali Kushwaha |
  As a researcher and change-maker I have dedicated years working in the field of urban sustainability, environmental management and complex systems thinking. 
  Lately, as a PhD candidate, I am developing frameworks, models, and recommendations for improving water security and resilience in Indian cities.

baseurl: ""
author: 
name: Vaishali Kushwaha
email: vaishali.kushwaha@gmail.com

#social links:
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
#github_username:  vaikush # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal



# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"


header_pages:
 - about.md

