title: COMPLEXCITY 
author: Vaishali Kushwaha
email: vaishali.kushwaha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creating awareness on complex issues that matter for our cities.
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  vaikush # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman

